use cab_bookings;
show tables;
describe uber_rides;
select * from uber_rides;


-- The total revenue generated by completed bookings in the last 6 months.
SELECT DATE_FORMAT(ride_date, '%Y-%m') AS month, SUM(CAST(Booking_Value AS DECIMAL(10,2))) AS total_revenue, COUNT(*) AS total_bookings
FROM uber_rides
WHERE Booking_Status = 'Completed' AND ride_date >= DATE_SUB((SELECT MAX(ride_date) FROM uber_rides), INTERVAL 6 MONTH)
GROUP BY month
ORDER BY month ASC;


-- Identify the top 3 most frequently traveled routes based on PickupLocation and DropoffLocation
SELECT Pickup_Location, Drop_Location, COUNT(*) AS total_rides
FROM uber_rides
GROUP BY Pickup_Location, Drop_Location
ORDER BY total_rides DESC
LIMIT 3;


-- Determine if higher-rated drivers tend to complete more trips and earn higher fares
SELECT CAST(Driver_Ratings AS DECIMAL(3,2)) AS driver_rating, COUNT(*) AS total_completed_trips, 
SUM(CAST(Booking_Value AS DECIMAL(10,2))) AS total_earnings, 
ROUND(AVG(CAST(Booking_Value AS DECIMAL(10,2))),2) AS avg_earning_per_trip
FROM uber_rides
WHERE Booking_Status = 'Completed' AND Driver_Ratings IS NOT NULL
GROUP BY CAST(Driver_Ratings AS DECIMAL(3,2))
ORDER BY driver_rating DESC;